version: "2"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplePassword
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      VIRTUAL_HOST: "iab330.rbvea.co"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "iab330.rbvea.co"
    ports:
      - 7009:8080
    command: "npm start"
    # command: "node tasks/createData.js"
